trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'Azure subscription 1'
  resourceGroupName: 'Test-Rg'
  deploymentName: 'suse-linux-vm-deployment'
  location: 'eastus'

stages:
  - stage: DeployVM
    displayName: 'Deploy SUSE Linux VM with Bicep'
    jobs:
      - job: Deploy
        displayName: 'Deploy VM Resources'
        pool:
          Devops_Agent

        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az group create --name $(resourceGroupName) --location $(location)

                az deployment group create \
                  --resource-group $(resourceGroupName) \
                  --name $(deploymentName) \
                  --template-file main.bicep \
                  --parameters @main.parameters.json
